/**
 * Versions of the app and of the tools it runs.
 *
 * The tool versions cannot be read at runtime. None of the Radiance tools the
 * pipeline ships prints its version, and `dcraw_emu`'s usage banner does not
 * carry LibRaw's, so the build is the only place that knows. They are recorded
 * in `public/wasm/versions.json`, generated by `scripts/wasm-versions.mjs`
 * from the fork checkouts the `.wasm` files were built from, and fetched from
 * the same origin as the artifacts they describe.
 */

/** Where the browser builds are served from. See `public/wasm/README.md`. */
const WASM_BASE_URL = "/wasm";

export interface ToolVersion {
  commit: string;
  /** `git describe` output, so a build between tags is still identifiable. */
  describe: string;
  repository: string;
  upstream?: string;
  version: string;
}

export interface WasmVersions {
  emscripten: string;
  tools: Record<string, ToolVersion>;
}

let cached: Promise<WasmVersions> | undefined;

/**
 * Reads the recorded tool versions.
 *
 * Cached for the session: the file describes committed artifacts and cannot
 * change while the app is running.
 */
export function wasmVersions(): Promise<WasmVersions> {
  cached ??= fetch(`${WASM_BASE_URL}/versions.json`).then((response) => {
    if (!response.ok) {
      throw new Error(
        `${WASM_BASE_URL}/versions.json returned ${response.status}. ` +
          "Run: node scripts/wasm-versions.mjs"
      );
    }
    return response.json() as Promise<WasmVersions>;
  });
  return cached;
}

/** The order the settings page lists them in: merge first, then corrections. */
export const TOOL_ORDER = ["hdrgen", "radiance", "dcraw_emu"] as const;

export const TOOL_LABELS: Record<string, string> = {
  dcraw_emu: "LibRaw (dcraw_emu)",
  hdrgen: "hdrgen",
  radiance: "Radiance",
};

/**
 * What each tool does, so the list explains itself.
 *
 * Worth stating because the whole point of the WebAssembly port is that a user
 * no longer installs any of these, and a bare version number for software they
 * never chose is not informative on its own.
 */
export const TOOL_ROLES: Record<string, string> = {
  dcraw_emu: "converts RAW files, and renders RAW previews",
  hdrgen: "merges the exposure bracket into an HDR image",
  radiance: "crops, resizes, applies the calibration files and measures glare",
};
